export enum ENV {
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_USERNAME = 'MYSQL_USERNAME',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',
  MYSQL_TYPE = 'MYSQL_TYPE',
  MYSQL_DATABASE = 'MYSQL_DATABASE',
}
